[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "gradio>=5.35.0",
    "langchain-core>=0.3.65",
    "langchain-openai>=0.3.24",
    "pymupdf==1.25.0",
]
langchain = "*"
openai = "*"
